############# English navigation ##############

# main menu
[[main]]
name = "Home / Blog"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 3

[[main]]
name = "Resources"
url = "/Resources"
weight = 4

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

# footer menu
[[footer]]
name = "Resources"
url = "/resources"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3